# Change these first
owner: calgo-lab # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
assignees:
  - se-jaeger
  - itrajanovska

sites:
  - name: calgo-lab.de
    url: https://calgo-lab.de
  - name: green-db.calgo-lab.de
    url: https://green-db.calgo-lab.de
  - name: product-classification.demo.calgo-lab.de
    url: https://product-classification.demo.calgo-lab.de

status-website:
  introTitle: "Cognitive Algorithms Lab Status & Uptime Monitoring"
  introMessage: This status page lists all services provided, hosted, and/or managed by the Cognitive Algorithms Lab team and checks their uptime every 5 minutes.
  cname: status.calgo-lab.de
  baseUrl: /
  theme: dark
  name: Cognitive Algorithms Lab Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Website
      href: https://calgo-lab.de

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

commitMessages:
  commitAuthorName: "calgo-lab (Bot)"
  commitAuthorEmail: "no-reply@calgo-lab.de"
